// Read − Reads the user's input, parses the input into JavaScript data-structure, and stores in memory.

// Eval − Takes and evaluates the data structure.

// Print − Prints the result.

// Loop − Loops the above command until the user presses ctrl-c twice.

//how to star repl --> type node in terminal
    // j.s Exparesan
    // use variable
    // multiline code/loop
    // use _ to get last result
    // we can use editor mod 